# Generated by Django 4.1.4 on 2022-12-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Id_name', models.CharField(max_length=20)),
                ('Mail', models.EmailField(max_length=150)),
                ('Mobile_number', models.IntegerField()),
            ],
        ),
    ]
