# Generated by Django 4.1.4 on 2022-12-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomnumber', models.IntegerField()),
                ('roomfloor', models.IntegerField()),
                ('roomtype', models.CharField(max_length=50)),
                ('select', models.CharField(max_length=50)),
                ('roomprice', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='add_user',
            name='Id_name',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='add_user',
            name='Mobile_number',
            field=models.CharField(max_length=12),
        ),
    ]
