# Generated by Django 4.1.4 on 2022-12-28 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_add_room_alter_add_user_id_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_room',
            new_name='add_roomm',
        ),
        migrations.RenameModel(
            old_name='add_user',
            new_name='add_userr',
        ),
    ]
